### ISSUE TITLE
Problem occured when integrating with Angular

### ISSUE THREAD

**Issue by TANK2003** [bimdata/bimdata-viewer-sdk#58]
I use BIM data with angular. All works fine, i can see my IFC's files. 
But when i click a button of my application or hover an element that have a "tooltip text" this error occured many times (100+)
`
core.js:5973 ERROR RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at f (bimdata-viewer.min.js:1)
    at bimdata-viewer.min.js:1
    at Array.map (<anonymous>)
    at f (bimdata-viewer.min.js:1)
    at bimdata-viewer.min.js:1
    at Array.map (<anonymous>)
    at f (bimdata-viewer.min.js:1)
    at bimdata-viewer.min.js:1
`

**Comment by Amoki** [comment]
Hi, thanks for the issue.

Do you have an example to reproduce the issue?

**Comment by TANK2003** [comment]
After the import of thiss library https://unpkg.com/@bimdata/viewer@1.5.2/dist/bimdata-viewer.min.js in the app, when ever i click on a button of the app it produce that error.

`
bimdata-viewer.min.js:17 Unable to preventDefault inside passive event listener invocation.
Y_.m.addEventListener._mouseWheelHandler @ bimdata-viewer.min.js:17
`

**Comment by Amoki** [comment]
Can you try with the npm package? https://www.npmjs.com/package/@bimdata/viewer
(We released a 1.5.3 yesterday which fix the 2D viewer)

I'm not familiar with Angular. If you can send a zip of a hello world project which triggers the issue (with the demo token or we'll be able to provide one), it could be awesome!

**Comment by TANK2003** [comment]
I have try, but not still working. I will create a zip file and send it to you tomorrow.
Thanks for your answers !

**Comment by TANK2003** [comment]
Hello,

You will find in attach a "hello world" angular project. We have only import the bimdata.js from  https://www.npmjs.com/package/@bimdata/viewer in the `angular.json` file

After `npm install` and `npm start ` open the browser to see the error in the console.

[bimdata-test.zip](https://github.com/bimdata/bimdata-viewer-sdk/files/6203534/bimdata-test.zip)

**Comment by Amoki** [comment]
Can you try with https://unpkg.com/@bimdata/viewer@1.6.0-rc.12/dist/bimdata-viewer.min.js ?

We don't know where this problem comes from, but it seems to be solved in our latest version.

The main difference with the 1.5.x is the 2Dviewer witch uses a brand new render engine but there is no API change

**Comment by TANK2003** [comment]
Fine it works now, thank you very much for this !
