### ISSUE TITLE
CORS header missing from authentication server

### ISSUE THREAD

**Issue by cyrilbele** [bimdata/bimdata-viewer-sdk#7]
Hi,

I installed the app, set the oidc-callback return url on my application and when I try to login, I accept to give permissions but on my way back to localhost I have url constently changing

http://localhost:8080/oidc-callback?state=a640f87b75154efdba18903354ea9b26&session_state=499e9201-49c8-4cf7-9764-3610e187f03f&code=de96a443-1284-47da-99f2-6ad4318ee0e9.499e9201-49c8-4cf7-9764-3610e187f03f.aec55c70-d676-444f-a578-6d4a5f1a2a9c
http://localhost:8080/oidc-callback?state=88ff9646f6ef49309086744a76af3e51&session_state=499e9201-49c8-4cf7-9764-3610e187f03f&code=3b96c250-77a2-46f6-8202-f80bfbbc61fa.499e9201-49c8-4cf7-9764-3610e187f03f.aec55c70-d676-444f-a578-6d4a5f1a2a9c

Looking at the console, it looks like CORS issue on the iam.bimdata.io server

Access to XMLHttpRequest at 'https://iam.bimdata.io/auth/realms/bimdata/protocol/openid-connect/token' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Amoki** [comment]
This appends when the access type of the app is 'Confidential' and you're trying to login with the implicit flow or the Authentication Code flow with PKCE.
Unfortunately, the CORS security triggers before the OIDC error, and the real error is hidden.
The SDK uses the Authentication Code flow with PKCE so I think that the problem.
